// const stockStickers = [
//   {
//     id: 1,
//     cantidad: 1,
//     nombre: "Mugiwara",
//     tamaño: "10x10",
//     precio: 200,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/mugiwara-min_cvzxg8.jpg",
//     anime: "One Piece",
//   },
//   {
//     id: 2,
//     cantidad: 1,
//     nombre: "Luffy",
//     tamaño: "8x8",
//     precio: 150,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/luffy-min_fyi0ke.png",
//     anime: "One Piece",
//   },
//   {
//     id: 3,
//     cantidad: 1,
//     nombre: "Zoro",
//     tamaño: "8x8",
//     precio: 150,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/zoro-min_ci5cin.jpg",
//     anime: "One Piece",
//   },
//   {
//     id: 4,
//     cantidad: 1,
//     nombre: "Goku",
//     tamaño: "8x8",
//     precio: 150,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/goku-min_f5pvuq.png",
//     anime: "Dragon Ball Z",
//   },
//   {
//     id: 5,
//     cantidad: 1,
//     nombre: "Vegeta",
//     tamaño: "6x6",
//     precio: 120,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/vegeta-min_zsgjly.png",
//     anime: "Dragon Ball Z",
//   },
//   {
//     id: 6,
//     cantidad: 1,
//     nombre: "Kid Buu",
//     tamaño: "6x6",
//     precio: 120,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759745/Stock%20Stickers%20Anime/boo-min_ks0mge.jpg",
//     anime: "Dragon Ball Z",
//   },
//   {
//     id: 7,
//     cantidad: 1,
//     nombre: "Tanjiro",
//     tamaño: "8x8",
//     precio: 150,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759747/Stock%20Stickers%20Anime/tanjiro-min_jceyqi.png",
//     anime: "Kimetsu no Yaiba",
//   },
//   {
//     id: 8,
//     cantidad: 1,
//     nombre: "Inosuke",
//     tamaño: "6x6",
//     precio: 120,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759746/Stock%20Stickers%20Anime/inosuke-min_gbiwkt.png",
//     anime: "Kimetsu no Yaiba",
//   },
//   {
//     id: 9,
//     cantidad: 1,
//     nombre: "Zenitsu",
//     tamaño: "6x6",
//     precio: 120,
//     imagen: "https://res.cloudinary.com/dbaqismy5/image/upload/v1667759747/Stock%20Stickers%20Anime/zenitsu-min_ae1zs3.png",
//     anime: "Kimetsu no Yaiba",
//   }
// ];

// export default stockStickers;